<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="G4SOptiPost" nsURI="http://www.misc.com/projects/g4s/optipost/model/0.1"
    nsPrefix="g4sop">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubDomains" upperBound="-1"
        eType="#//Domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shifts" upperBound="-1"
        eType="#//Shift" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employees" upperBound="-1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenarios" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shift">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employee" eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShiftStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShiftEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EmployeeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LocationID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpOptiPostFlows" upperBound="-1"
        eType="#//LpOptiPostFlow" containment="true" eOpposite="#//LpOptiPostFlow/Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedShifts" upperBound="-1"
        eType="#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpOptiPostFlow" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Generator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpRoot" eType="#//LpRoot"
        containment="true" eOpposite="#//LpRoot/LpOptiPostFlow"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinOverlapPredecessor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.25"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinOverlapSuccessor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.25"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenario" eType="#//Scenario"
        eOpposite="#//Scenario/LpOptiPostFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CplexSolver" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.cplex.emf/model/solvercplex.ecore#//SolverCplex"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpRoot" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Precedences" upperBound="-1"
        eType="#//LpPrecedence" containment="true" eOpposite="#//LpPrecedence/LpRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Jobs" upperBound="-1" eType="#//LpJob"
        containment="true" eOpposite="#//LpJob/LpRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpOptiPostFlow" eType="#//LpOptiPostFlow"
        eOpposite="#//LpOptiPostFlow/LpRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpEmployees" upperBound="-1"
        eType="#//LpEmployee" containment="true" eOpposite="#//LpEmployee/LpRoot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpJob" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shift" eType="#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobsAfter" upperBound="-1"
        eType="#//LpPrecedence" eOpposite="#//LpPrecedence/JobBefore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobsBefore" upperBound="-1"
        eType="#//LpPrecedence" eOpposite="#//LpPrecedence/JobAfter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartOfMonth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndOfMonth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpRoot" eType="#//LpRoot"
        eOpposite="#//LpRoot/Jobs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpEmployee" lowerBound="1"
        eType="#//LpEmployee" eOpposite="#//LpEmployee/LpJobs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConsIsFollowedInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConsIsPrecededInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpPrecedence" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobBefore" lowerBound="1"
        eType="#//LpJob" eOpposite="#//LpJob/JobsAfter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobAfter" lowerBound="1"
        eType="#//LpJob" eOpposite="#//LpJob/JobsBefore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpRoot" eType="#//LpRoot"
        eOpposite="#//LpRoot/Precedences"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpEmployee" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpRoot" eType="#//LpRoot"
        eOpposite="#//LpRoot/LpEmployees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpJobs" upperBound="-1"
        eType="#//LpJob" eOpposite="#//LpJob/LpEmployee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employee" lowerBound="1"
        eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinNrJobs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="20"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConsEnoughJobsInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
