<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="G4SOptiPost" nsURI="http://www.misc.com/projects/g4s/optipost/model/0.1"
    nsPrefix="g4sop">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubDomains" upperBound="-1"
        eType="#//Domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shifts" upperBound="-1"
        eType="#//Shift" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employees" upperBound="-1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenarios" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobsImporter" upperBound="-1"
        eType="#//JobsImporter" containment="true" eOpposite="#//JobsImporter/Domain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Spreadsheets" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.spreadsheet.poi.emf/model/spreadsheetpoi.ecore#//SpreadsheetPOI"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shift">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employee" eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShiftDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShiftStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShiftEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EmployeeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LocationID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpOptiPostFlows" upperBound="-1"
        eType="#//LpOptiPostFlow" containment="true" eOpposite="#//LpOptiPostFlow/Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedShifts" upperBound="-1"
        eType="#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solutions" upperBound="-1"
        eType="#//OptiPostSolution" containment="true" eOpposite="#//OptiPostSolution/Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbsoluteMinEmployeeNrJob"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbsoluteMaxEmployeeNrJobs"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is an upper bound on the minumun nr of jobs an employee has to do in a month to qualify."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaxOverlapPredecessor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.25"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaxOverlapSuccessor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.25"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CplexSolver" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.cplex.emf/model/solvercplex.ecore#//SolverCplex"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpOptiPostFlow" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Generator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpRoot" eType="#//LpRoot"
        containment="true" eOpposite="#//LpRoot/LpOptiPostFlow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenario" eType="#//Scenario"
        eOpposite="#//Scenario/LpOptiPostFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GoalNofEmployees" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpRoot" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Jobs" upperBound="-1" eType="#//LpJob"
        containment="true" eOpposite="#//LpJob/LpRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpOptiPostFlow" eType="#//LpOptiPostFlow"
        eOpposite="#//LpOptiPostFlow/LpRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpEmployees" upperBound="-1"
        eType="#//LpEmployee" containment="true" eOpposite="#//LpEmployee/LpRoot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpJob" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shift" eType="#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobsAfter" upperBound="-1"
        eType="#//LpPrecedence" eOpposite="#//LpPrecedence/JobBefore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobsBefore" upperBound="-1"
        eType="#//LpPrecedence" containment="true" eOpposite="#//LpPrecedence/JobAfter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartOfMonth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndOfMonth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpRoot" eType="#//LpRoot"
        eOpposite="#//LpRoot/Jobs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpEmployee" lowerBound="1"
        eType="#//LpEmployee" eOpposite="#//LpEmployee/LpJobs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConsIsFollowedInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConsIsPrecededInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarIsFirstInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarIsLastInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpPrecedence" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobBefore" lowerBound="1"
        eType="#//LpJob" eOpposite="#//LpJob/JobsAfter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobAfter" lowerBound="1"
        eType="#//LpJob" eOpposite="#//LpJob/JobsBefore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpEmployee" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpRoot" eType="#//LpRoot"
        eOpposite="#//LpRoot/LpEmployees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpJobs" upperBound="-1"
        eType="#//LpJob" eOpposite="#//LpJob/LpEmployee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employee" lowerBound="1"
        eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinNrJobs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MinNrJobs is the numbers of jobs the employee has to do in the month to qualify for the benefit&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConsEnoughJobsInPost" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobsImporter" abstract="true">
    <eOperations name="formatWorkerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="idAsInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getOrCreateEmployee" eType="#//Employee">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOrCreateLocation" eType="#//Location">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createJob" eType="#//Shift">
      <eParameters name="employee" eType="#//Employee"/>
      <eParameters name="location" eType="#//Location"/>
      <eParameters name="shiftDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="shiftStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="shiftEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="importJobs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Domain" eType="#//Domain"
        eOpposite="#//Domain/JobsImporter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobsImporterSpreadsheet" eSuperTypes="#//JobsImporter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Spreadsheet" eType="ecore:EClass ../../com.misc.common.moplaf.spreadsheet.emf/model/spreadsheet.ecore#//Spreadsheet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataSheetNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WorkerIdColNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LocationIdColNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="JobDateColNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="12"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="JobStartColNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="JobEndColNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LocationDescriptionColNr"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="9"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptiPostSolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Lp" eType="#//LpOptiPostFlow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Posts" upperBound="-1"
        eType="#//OptiPostSolutionPost" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employees" upperBound="-1"
        eType="#//OptiPostSolutionEmployee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NrEmployees" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EmployeesInPost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShiftsInPost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenario" eType="#//Scenario"
        eOpposite="#//Scenario/Solutions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptiPostSolutionPost">
    <eOperations name="addShift" eType="#//OptiPostSolutionShift">
      <eParameters name="shift" eType="#//Shift"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shifts" upperBound="-1"
        eType="#//OptiPostSolutionShift" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NrShifts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptiPostSolutionEmployee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shifts" upperBound="-1"
        eType="#//OptiPostSolutionShift"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Employee" eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NrShifts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InPost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptiPostSolutionShift">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shift" eType="#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
